# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - 'rewrite/alpha'

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/Quarrel.App.sln'
  buildPlatform: 'x86|x64|arm|arm64'
  buildConfiguration: 'Alpha'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
  buildDir: '$(build.artifactStagingDirectory)\build\\'
  msixUploads: '$(appxPackageDir)\**\\*.msixupload'
  msixBundles: '$(appxPackageDir)\**\\*.msixbundle'
  msixPackages: '$(appxPackageDir)\**\\*.msix'
  appInstaller: '$(appxPackageDir)\Quarrel.appinstaller'

steps:
- task: DownloadSecureFile@1
  displayName: Get Signing Certificate
  name: signingCertificate
  inputs:
    secureFile: 'Quarrel-Alpha_Key.pfx'
- task: DownloadSecureFile@1
  displayName: Get AppCenterToken
  name: appCenterToken
  inputs:
    secureFile: 'AppCenterAlpha.json'

- task: PowerShell@2
  displayName: Place AppCenterToken
  inputs:
    targetType: 'inline'
    script: 'Copy-Item $Env:APP_CENTER_TOKEN_PATH -Destination "$($Env:BUILD_SOURCESDIRECTORY)/src/Quarrel/Assets/Tokens/AppCenter/"'
  env:
    APP_CENTER_TOKEN_PATH: $(appCenterToken.secureFilePath)

- task: NuGetToolInstaller@1
  displayName: 'NuGet Installer'

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(solution)'
    platform: 'x64'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Quarrel
                  /p:AppxBundlePlatforms="$(buildPlatform)"
                  /p:AppxPackageDir="$(appxPackageDir)"
                  /p:OutputPath="$(buildDir)"
                  /p:AppxBundle=Always
                  /p:AppxPackageSigningEnabled=true
                  /p:PackageCertificateKeyFile="$(signingCertificate.secureFilePath)"
                  /p:PackageCertificateThumbprint="$(SignedCertificateThumbprint-Alpha)" 
                  /p:PackageCertificatePassword="$(SignCertificatePassword-Alpha)"'

- task: GitHubRelease@1
  displayName: 'Create GitHub release'
  inputs:
    gitHubConnection: 'Avid29'
    repositoryName: 'UWPCommunity/Quarrel'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tag: "alpha-v$(Build.BuildNumber)"
    tagSource: 'userSpecifiedTag'
    title: 'Alpha-v$(Build.BuildNumber)'
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    assets: |
      $(msixUploads)
      $(msixBundles)
      $(msixPackages)
      $(appInstaller)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'