# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
    exclude:
    - "rewrite/alpha"
  paths:
    include:
    - src/*
    exclude:
    - src/Quarrel/Strings/*
    - src/Quarrel/MultilingualResources/*
    - src/Quarrel/Assets/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/Quarrel.sln'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1
  displayName: "Install NuGet" 

- task: NuGetCommand@2
  displayName: "NuGet Restore" 
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: "Build.x64" 
  inputs:
    solution: '$(solution)'
    platform: 'x64'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'

- task: VSBuild@1
  displayName: "Build.ARM64" 
  inputs:
    solution: '$(solution)'
    platform: 'ARM64'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'